accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'(?P<pk>\d+)/$', views.buy_book, name="buy"),
]

bookshop/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('shop/', include('shop.urls', namespace='shop')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

shop/urls.py
from django.conf.urls import url

from . import views

app_name = 'shop'

urlpatterns = [
    url(r'(?P<pk>\d+)/$', views.view_book, name="view"),
    url(r'^$', views.display_all_books, name="all"),
]

accounts/models.py
from django.db import models

from shop.models import Book

# Create your models here.
class Order(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    customer = models.CharField(max_length=100)
    charge = models.DecimalField(decimal_places=2, max_digits=6)

shop/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=100)
    category = models.CharField(max_length=30)
    price = models.DecimalField(decimal_places=2, max_digits=6)
    blurb = models.TextField()
    author = models.CharField(max_length=30)
    created_at = models.DateField()

accounts/views.py
from django.shortcuts import get_object_or_404, render

from shop.models import Book

# Create your views here.
def buy_book(request, pk):
    book = get_object_or_404(Book, pk=pk)
    return render(request, "accounts/invoice.html", {"book": book})

bookshop/views.py
from django.http import HttpResponse
import datetime

def home(request):
    now = datetime.datetime.now()
    html = "<html><body><h1>Welcome to the bookshop!</h1><h2>It is now %s.<h2></body></html>" % now        
    return HttpResponse(html)

shop/views.py
from django.shortcuts import get_object_or_404, render

from .models import Book

# Create your views here.
def display_all_books(request):
    books = Book.objects.all()
    return render(request, "shop/display_all_books.html" ,{"books": books})

def view_book(request, pk):
    book = get_object_or_404(Book, pk=pk)
    return render(request, "shop/view_book.html", {"book": book})

accounts/templates/accounts/invoice.html
<!doctype html>
<html>
    <head>
        <title>Accounts</title>
        <meta http-equiv="content-type" content="text/html">
    </head>

    <body>
        <p>You have bought <strong>{{ book.title }}</strong> for <strong>€{{ book.price }}</strong></p>

        <a href="{% url 'shop:all' %}">Return to shop</a>
    </body>
</html>

shop/templates/shop/display_all_books.html
<!doctype html>
<html>
    <head>
        <title>Shop</title>
        <meta http-equiv="content-type" content="text/html">
    </head>

    <body>
        {% for book in books %}
            <a href="{% url 'shop:view' pk=book.pk %}"><h2>{{ book.title }}</h2></a>
            <h3>{{ book.author }}</h3>
            <h2>{{ book.price }}</h2>
        {% endfor %}
    </body>
</html>

shop/templates/shop/view_book.html
<!doctype html>
<html>
    <head>
        <title>Shop</title>
        <meta http-equiv="content-type" content="text/html">
    </head>

    <body>
        <h1>{{ book.title }}</h1>
        <h2>{{ book.author }}</h2>
        <h3>{{ book.category }}</h3>
        <p>{{ book.blurb }}</p>
        <h1>€{{ book.price }}</h1>

        <a href="{% url 'accounts:buy' pk=book.pk %}"><h1>Buy</h1></a>
    </body>
</html>